//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReChat
{
    using System;
    using System.Collections.Generic;
    using System.Security.Principal;

    public partial class User : IPrincipal
    {

        public User()
        {

        }

        public User(string login, string token, string pwd, bool ban)
        {
            Login = login;
            Token = token;
            Password = pwd;
            IsBaned = ban;

            RegDate = DateTime.Now;
            FirstName = " ";
            LastName = " ";
            Email = " ";
            Cookies = " ";
        }

        public int Id { get; set; }
        public System.DateTime RegDate { get; set; }
        public string Login { get; set; }
        public string Token { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Cookies { get; set; }
        public string Password { get; set; }
        public bool IsBaned { get; set; }
        public int idRole { get; set; }

        public IIdentity Identity
        {
            get { return new GenericIdentity("  "); }
        }

        public bool IsInRole(string role)
        {
            return role == "user";
        }
    }
}
